DROP TABLE DUAL;

CREATE TABLE DUAL (
  dummy VARCHAR(30),
  CONSTRAINT dummy PRIMARY KEY(dummy)
);


INSERT INTO DUAL
  VALUES('dummyOuch');

/*   WARNING DUAL TABLE IS CONTAIN JUST ONE COLUMN AND ON RECORD FOT TESTING (TEST INSIDE rowFunctions.sql file)  */
